import { PropsWithChildren } from 'react'

import '@/styles/global.css'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children = null }: PropsWithChildren<{}>) {
	return (
		<html lang="ru">
			<body>{children}</body>
		</html>
	)
}
